name: Main

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  create-proj:
 
    runs-on: self-hosted
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make envfile
      run: |
        echo "SECRET_KEY=""${{ secrets.SECRET_KEY }}" >> .env
        echo "DB_NAME=""${{ secrets.DB_NAME }}" >> .env
        echo "DB_HOST=""${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=""${{ secrets.DB_PORT }}" >> .env
        echo "DB_USER=""${{ secrets.DB_USER }}" >> .env
        echo "DB_PASS=""${{ secrets.DB_PASS }}" >> .env
        echo "REDIS_HOST=""${{ secrets.REDIS_HOST }}" >> .env
        echo "REDIS_PORT=""${{ secrets.REDIS_PORT }}" >> .env
        echo "EMAIL_HOST_USER=""${{ secrets.EMAIL_HOST_USER }}" >> .env
        echo "EMAIL_HOST_PASSWORD=""${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
  
    - name: Build and run services
      run: |
        docker compose down
        docker compose up -d --build

    - name: Check running containers
      run: docker ps